[tool.isort]
multi_line_output = 3
line_length = 119
include_trailing_comma = true
known_third_party = []

[tool.mypy]
incremental = true
warn_redundant_casts = true
disallow_subclassing_any = true
warn_unused_configs = true
ignore_missing_imports = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
no_implicit_optional = true
warn_return_any = true
warn_unused_ignores = true
strict_optional = true

[tool.black]
line-length = 119
